server.port: 8080

logging:
  level:
    root: ERROR
    com.board.thymeleaf: DEBUG

spring:
  profiles:
    active: local       #local, dev, real
  servlet.multipart:
    max-file-size: 1024MB
    max-request-size: 1024MB

# mybatis 설정
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR
  type-aliases-package:
    com.board.thymeleaf.domain
  mapper-locations:
   - com/board/thymeleaf/mapper/board/**/*.xml
   - com/board/thymeleaf/mapper/common/**/*.xml